"""Monitoring module for health checks, metrics, and observability."""

from .health import (
    HealthChecker,
    HealthStatus,
    HealthReport,
    ServiceHealth,
    ModelHealth,
    ToolHealth,
    check_health,
    run_health_server,
)

from .metrics import (
    MetricsCollector,
    MetricSnapshot,
    get_metrics_collector,
    reset_metrics_collector,
    record_request_start,
    record_request_end,
    record_token_usage,
    record_tool_call,
    get_metrics,
    get_metrics_summary,
    start_metrics_server,
    run_metrics_server_sync,
)

from .alerts import (
    AlertLevel,
    Alert,
    AlertRule,
    AlertManager,
    AlertHandler,
    LogHandler,
    ConsoleHandler,
    WebhookHandler,
    HighFailureRateRule,
    HighLatencyRule,
    TokenBudgetRule,
    ToolFailureRule,
    get_alert_manager,
    reset_alert_manager,
    check_alerts,
    get_active_alerts,
    acknowledge_alert,
)

from .tracing import (
    TracingManager,
    TraceRecord,
    TraceStorage,
    get_tracing_manager,
    reset_tracing_manager,
    start_span,
    traced,
    trace_tool_call,
    trace_llm_call,
    trace_agent_node,
    trace_subagent,
    get_trace_storage,
    get_recent_traces,
    get_trace_tree,
)

__all__ = [
    # Health
    "HealthChecker",
    "HealthStatus",
    "HealthReport",
    "ServiceHealth",
    "ModelHealth",
    "ToolHealth",
    "check_health",
    "run_health_server",
    # Metrics
    "MetricsCollector",
    "MetricSnapshot",
    "get_metrics_collector",
    "reset_metrics_collector",
    "record_request_start",
    "record_request_end",
    "record_token_usage",
    "record_tool_call",
    "get_metrics",
    "get_metrics_summary",
    "start_metrics_server",
    "run_metrics_server_sync",
    # Alerts
    "AlertLevel",
    "Alert",
    "AlertRule",
    "AlertManager",
    "AlertHandler",
    "LogHandler",
    "ConsoleHandler",
    "WebhookHandler",
    "HighFailureRateRule",
    "HighLatencyRule",
    "TokenBudgetRule",
    "ToolFailureRule",
    "get_alert_manager",
    "reset_alert_manager",
    "check_alerts",
    "get_active_alerts",
    "acknowledge_alert",
    # Tracing
    "TracingManager",
    "TraceRecord",
    "TraceStorage",
    "get_tracing_manager",
    "reset_tracing_manager",
    "start_span",
    "traced",
    "trace_tool_call",
    "trace_llm_call",
    "trace_agent_node",
    "trace_subagent",
    "get_trace_storage",
    "get_recent_traces",
    "get_trace_tree",
]
